 $(document).ready(function()
       	{
       		$("#change-1").click(function()
       			{
       				$("#main").removeClass('wrap2').removeClass('wrap3');
       				$("#main").addClass("wrap1");
       			});
       		$("#change-2").click(function()
       			{
       				$("#main").removeClass('wrap1').removeClass('wrap3');
       				$("#main").addClass("wrap2");
       			});
       		$("#change-3").click(function()
       			{
       				$("#main").removeClass('wrap1').removeClass('wrap2');
       				$("#main").addClass("wrap3");
       			});
       		$("#btnid").click(function()
       		{
                    $("#main").removeClass('wrap1').removeClass('wrap2').removeClass('wrap3');
       		});
       	});